VirtualTable/Models/ErrorViewModel.cs
namespace VirtualTable.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VirtualTable/Controllers/AddValueController.cs
using System.Collections.Generic;
using Infrastructure;
using Infrastructure.DTO;
using Microsoft.AspNetCore.Mvc;
using Service.Addvalue;
using VirtualTable.Mapper;

namespace VirtualTable.Controllers
{
    public class AddValueController : Controller
    {
        IAddValue _service;
        public AddValueController(IAddValue service )
        {
            _service = service;
        }

        /// <summary>
        /// create page to choose table
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult ChooseTable()
        {
            var list = Map.TableList(_service.AllTable());

            return View(list) ;
        }

        /// <summary>
        /// seed data in database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult SeedData(int id)
        {
            var model =Map.TypeList( _service.TableData(id));
            return View(model);
        }
        [HttpPost]
        public IActionResult SeedData(List<ValueDto> values, List<TypesDto> model)
        {
            
            model = Map.TypeList(values);            
            if (ModelState.IsValid)
            {
                
                var error = _service.AddToValueTable(values);
                if (error == Massage.IsOk) return RedirectToAction("Index", "Home");
                ViewData["ErrorMessage"] = error;
                return View(model);
            }
            ViewData["ErrorMessage"] = Massage.FillFields;
            return View(model);
        }
        
}    
}

VirtualTable/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VirtualTable.Models;
// ReSharper disable All

namespace VirtualTable.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VirtualTable/Controllers/NewTableController.cs
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Service.AddNewTable;
using VirtualTable.Mapper;
using VirtualTable.ViewModel;

namespace VirtualTable.Controllers
{
    public class NewTableController : Controller
    {
        private readonly IAddTable _service;
        public NewTableController(IAddTable service)
        {
            _service = service;
        }



        [HttpGet]
        public IActionResult AddNewTable()
        {
            var table = new TableView();
            return View(table);
            
        }

        [HttpPost]
        public ActionResult AddNewTable(TableView model)
        {
            if (!ModelState.IsValid) return View("AddNewTable", model);
            var types = Map.TypeList(model);
            var error=_service.AddInformationToDatabase(model.TableName, types);
            if (error == Massage.IsOk) return RedirectToAction("Index", "Home");
            ViewData["ErrorMessage"] = error;
            return View("AddNewTable", model);
        }


    }
}

VirtualTable/Controllers/ShowInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Service.ShowInformation;
using VirtualTable.Mapper;

namespace VirtualTable.Controllers
{
    public class ShowInfoController : Controller
    {
        private readonly IShowInfo _service;
        public ShowInfoController(IShowInfo service )
        {
            _service = service;
        }
        /// <summary>
        /// show data of table 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult ShowData(int id)
        {
            ViewData["column"] = _service.AllType(id);
            var values =Map.ValueList(_service.ValueOfTable(id));
            return View(values);
        }

       
    }
}

VirtualTable/Views/AddValue/ChooseTable.cshtml
@model List<Infrastructure.DTO.TableDto>
@{ ViewData["Title"] = "ChooseTable"; }


<h1>جدول ها </h1>

@foreach (var item in Model)
{
<div class="card mb-3 ">
    <div class="card-body" style="background-color:aqua">
        <h5 class="card-title">نام جدول : @(item.TableName) </h5>
    </div>
    <div class="card-footer font-weight-bold text-black-50">
        <a asp-controller="AddValue" asp-action="SeedData" asp-route-id=@item.Id class="btn btn-warning"> اضافه کردن داده</a>
        <a asp-controller="ShowInfo" asp-action="ShowData" asp-route-id=@item.Id class="btn btn-success"> نمایش داده های جدول</a>
    </div>


</div>}

VirtualTable/Views/AddValue/SeedData.cshtml
@model List<Infrastructure.DTO.TypesDto>
@{ ViewData["Title"] = "SeedData"; }

<h1>SeedData</h1>


@if (ViewData["ErrorMessage"] != null)
{
<div class="text-danger float-right" dir="rtl">@ViewData["ErrorMessage"]</div>
                <br />
}



<div>
    <form asp-controller="AddValue" asp-action="SeedData" method="post">

        @for (int i = 0; i < Model.Count; i++)
        {

<div class="form-group ">
    <label  class="control-label font-weight-bold " style="color: limegreen">@Model[i].FieldName  (@Model[i].FieldType)</label>
    <div>
        <input type="hidden" value="@Model[i].FieldName" name="values[@i].Column" class="form-control border-dark col-md-3" style="margin-right:12px" />
        <input type="hidden" value="@Model[i].TableId" name="values[@i].TableId" class="form-control border-dark col-md-3" style="margin-right:12px" />
        <input type="hidden" value="@Model[i].FieldType" name="values[@i].Type" class="form-control border-dark col-md-3" style="margin-right:12px" />
        <input type="text" value="@Model[i].Value" name="values[@i].FieldValue" class="form-control border-dark col-md-3" style="margin-right:12px" />
        
    </div>
</div>}


        <div class="form-group ml-3 mt-2">
            <button type="submit" class="btn btn-primary btn-success">ثبت</button>
        </div>
    </form>
</div>

VirtualTable/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="btn btn-success">

    <a style="color:black" asp-area="" asp-controller="NewTable" asp-action="AddNewTable">اضافه کردن جدول</a>
</div>
<br />
<div class="btn btn-warning">
    <a style="color:black" asp-area="" asp-controller="AddValue" asp-action="ChooseTable">      جدول ها </a>
</div>

VirtualTable/Views/NewTable/AddNewTable.cshtml
@using VirtualTable.ViewModel;
@model VirtualTable.ViewModel.TableView;
@{ ViewData["Title"] = "AddNewTable"; }

@if (ViewData["ErrorMessage"] != null)
{
<div class="text-danger float-right" dir="rtl">@ViewData["ErrorMessage"]</div>
                <br />
 } @*<script type="text/javascript" src="./lib/jquery/dist/jquery.min.js"></script>*@
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $(".addRow").click(function () {

            var rowCount = $('.phoneRow').length;
            if (rowCount == 0) {
                $("#phoneList").append('<span>اسم ستون       متغیر</span>');
            }
            $("#phoneList").append('<div class="phoneRow"><select name="TypeList[' + rowCount + '].Type" class="phoneType">@foreach (SelectListItem item in new TypeList().TypeSelectListItems){<option value="@item.Value">@item.Text</option>}</select><input type="text" name="TypeList[' + rowCount + '].ColumnName" class="phoneNumber" /><a href="javascript:void(0);" class="remRow">حذف</a></div>');
        });

        $("#phoneList").on('click', '.remRow', function () {

            $(this).closest('.phoneRow').remove();

            $('.phoneType').each(function (index) {
                $(this).attr('name', 'TypeList[' + index + '].Type');
            });

            $('.phoneNumber').each(function (index) {
                $(this).attr('name', 'TypeList[' + index + '].ColumnName');
            });
        })
    });
</script>

<h1>Create Table</h1>

<form action="/NewTable/AddNewTable" method="post">


    <p>
        @Html.LabelFor(model => model.TableName)
        @Html.TextBoxFor(model => model.TableName)
        @Html.ValidationMessageFor(model => model.TableName)
    </p>


    <div id="phoneList">
        @if (Model.TypeList.Count > 0)
        {
<span>اسم ستون       متغیر</span>}
        @for (int i = 0; i < Model.TypeList.Count; i++)
        {
<div class="phoneRow">
    @Html.DropDownList("TypeList[" + i + "].Type", Model.TypeList[i].TypeSelectListItems, new { @class = "phoneType" })

    @Html.TextBoxFor(model => Model.TypeList[i].ColumnName, new { @class = "phoneNumber" })
    @Html.ValidationMessageFor(model => Model.TypeList[i].ColumnName)

    <a href="javascript:void(0);" class="remRow">حذف</a>
</div>}
    </div>

    <p>
        <a href="javascript:void(0);" class="addRow">اضافه کردن ستون</a>
    </p>

    <p>
        <input type="submit" name="btnSubmit" value="Submit" class="btn-primary" />
    </p>

</form>

VirtualTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VirtualTable</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VirtualTable</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - VirtualTable - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

VirtualTable/Views/ShowInfo/ShowData.cshtml
@model List<Infrastructure.DTO.ValueDto>
@{ ViewData["Title"] = "ShowData";
    var column = ViewData["column"] as List<string>;
    int xt = column.Count;
    int ct = 0; }
<head>
    <style>
        table, td, th {
            border: 1px solid #ddd;
            text-align: left;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 15px;
        }

        th {
            background-color: dodgerblue;
            color: white;
        }

        td {
            background-color: antiquewhite;
            color: black;
        }
    </style>
</head>

<body>
    @if (column.Count != 0)
    {
<table>
    <tr>
        @foreach (var item1 in column)
        {


<th>@item1</th>
}
    </tr>

    @for (int i = 0; i < Model.Count / column.Count; i++)
    {

<tr>
    @for (int j = ct; j < xt; j++)
    {
<td>@Model[j].FieldValue</td>
}
</tr>
ct += column.Count;
xt += column.Count;
}

</table> }
else
{
<h1>دیتایی در این جدول وجود ندارد</h1>}
</body>